CicleFem1/Controllers/DettaglioSchedasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CicleFem1.Models;

namespace CicleFem1.Controllers
{
    public class DettaglioSchedasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DettaglioSchedas
        public ActionResult Index()
        {
            return View(db.DettaglioSchedas.ToList());
        }

        // GET: DettaglioSchedas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DettaglioScheda dettaglioScheda = db.DettaglioSchedas.Find(id);
            if (dettaglioScheda == null)
            {
                return HttpNotFound();
            }
            return View(dettaglioScheda);
        }

        // GET: DettaglioSchedas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DettaglioSchedas/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DettaglioScheda_Id,Data,Giorno,Temperatura,Scheda_Id,Ematic,Muco,MucoC,Coito,UteCon,UteInc,UteApe,UtePos,Sensazione,Note")] DettaglioScheda dettaglioScheda)
        {
            if (ModelState.IsValid)
            {
                db.DettaglioSchedas.Add(dettaglioScheda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dettaglioScheda);
        }

        // GET: DettaglioSchedas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DettaglioScheda dettaglioScheda = db.DettaglioSchedas.Find(id);
            if (dettaglioScheda == null)
            {
                return HttpNotFound();
            }
            return View(dettaglioScheda);
        }

        // POST: DettaglioSchedas/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DettaglioScheda_Id,Data,Giorno,Temperatura,Scheda_Id,Ematic,Muco,MucoC,Coito,UteCon,UteInc,UteApe,UtePos,Sensazione,Note")] DettaglioScheda dettaglioScheda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dettaglioScheda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Schedas", new { id = dettaglioScheda.Scheda_Id });
            }
            return View(dettaglioScheda);
        }

        // GET: DettaglioSchedas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DettaglioScheda dettaglioScheda = db.DettaglioSchedas.Find(id);
            if (dettaglioScheda == null)
            {
                return HttpNotFound();
            }
            return View(dettaglioScheda);
        }

        // POST: DettaglioSchedas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DettaglioScheda dettaglioScheda = db.DettaglioSchedas.Find(id);
            db.DettaglioSchedas.Remove(dettaglioScheda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CicleFem1/Controllers/SchedasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CicleFem1.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace CicleFem1.Controllers
{
    [Authorize]
    public class SchedasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore, DateFormatString = "dd/MM/yy" };

        // GET: Schedas
        public ActionResult Index()
        {
            var ut = User.Identity.GetUserId();
            return View(db.Schedas.Where(u => u.Uid == ut).OrderByDescending(d => d.DataI).ToList());
        }

        public ActionResult IndexUt()
        {
            var ut = User.Identity.GetUserId();
            return View(db.Schedas.Where(u=>u.Uid == ut).OrderByDescending(d => d.DataI).ToList());
        }

        // GET: Schedas/Details/5e
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheda scheda = db.Schedas.Find(id);
            if (scheda == null)
            {
                return HttpNotFound();
            }
            var dati = db.DettaglioSchedas.Where(s => s.Scheda_Id == id).Select(s => new { g = s.Giorno, t = s.Temperatura, m = s.Muco, mc = s.MucoC, e = s.Ematic, d = s.Data }).ToList();
            ViewBag.DataPoints = JsonConvert.SerializeObject(dati, _jsonSetting);
            return View(scheda);
        }

        public ActionResult TestChart(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheda scheda = db.Schedas.Find(id);
            if (scheda == null)
            {
                return HttpNotFound();
            }
            var dati = db.DettaglioSchedas.Where(s => s.Scheda_Id == id).Select(s => new { g = s.Giorno, t = s.Temperatura, m = s.Muco, e = s.Ematic, d = s.Data }).ToList();
            ViewBag.DataPoints = JsonConvert.SerializeObject(dati, _jsonSetting);
            return View(scheda);
        }

        // GET: Schedas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Schedas/Create
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Scheda_Id,Numero,NumeroG,DataI,DataF,Uid")] Scheda scheda, [Bind(Include = "DettaglioScheda_Id,Data,Giorno,Temperatura,Scheda_Id")] DettaglioScheda dettaglioScheda)
        {
            var ut = User.Identity.GetUserId();
            scheda.Uid = ut;
            var num = db.Schedas.Where(u => u.Uid == ut).Max(n => n.Numero);
            if(num != null)
            {
            scheda.Numero = num + 1;
            }
            else
            {
                scheda.Numero = 1;
            }
            double giorniadd = (double)scheda.NumeroG;
            scheda.DataF =  scheda.DataI.AddDays(giorniadd);
            var inizio = scheda.DataI;
            var giorni = scheda.NumeroG;
            if (ModelState.IsValid)
            {
                db.Schedas.Add(scheda);
                db.SaveChanges();
                //Creo una riga di dettaglio scheda in base al numero di giorni previsto
                for (int i = 0; i < giorni; i++)
                {
                    dettaglioScheda.Data = inizio.AddDays(i);
                    dettaglioScheda.Giorno = i + 1;
                    dettaglioScheda.Scheda_Id = scheda.Scheda_Id;
                    db.DettaglioSchedas.Add(dettaglioScheda);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(scheda);
        }

        // GET: Schedas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheda scheda = db.Schedas.Find(id);
            if (scheda == null)
            {
                return HttpNotFound();
            }
            return View(scheda);
        }

        // POST: Schedas/Edit/5
        // Per proteggere da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per ulteriori dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Scheda_Id,Numero,NumeroG,DataI,DataF,Uid")] Scheda scheda)
        {
            if (ModelState.IsValid)
            {

                db.Entry(scheda).State = EntityState.Modified;
                db.SaveChanges();
                db.DettaglioSchedas.RemoveRange(db.DettaglioSchedas.Where(d=>d.Scheda_Id == scheda.Scheda_Id && d.Data > scheda.DataF));
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(scheda);
        }

        // GET: Schedas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheda scheda = db.Schedas.Find(id);
            if (scheda == null)
            {
                return HttpNotFound();
            }
            return View(scheda);
        }

        // POST: Schedas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Scheda scheda = db.Schedas.Find(id);
            db.Schedas.Remove(scheda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CicleFem1/Views/Schedas/Delete.cshtml
@model CicleFem1.Models.Scheda

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Scheda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uid)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CicleFem1/Views/Schedas/Details.cshtml
@model CicleFem1.Models.Scheda

@{
    ViewBag.Title = "Details";
}

<h2>Dati scheda N.@Model.Numero</h2>

<div>
    <h4>
        <span class="label label-info">
            dal @Html.DisplayFor(model => model.DataI)
            al @Html.DisplayFor(model => model.DataF)
        </span>
    </h4>
</div>




<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#grafico" aria-controls="grafico" role="tab" data-toggle="tab">Grafico</a></li>
        <li role="presentation"><a href="#dati" aria-controls="dati" role="tab" data-toggle="tab">Dati</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <!--Tab grafico-->
        <div role="tabpanel" class="tab-pane active" id="grafico">
            <canvas id="myChart" ></canvas>
            @*Tabelle dati sotto il  grafico*@
            <div class="row">
                <table class="table table-bordered" style="font-size:0.7em">
                    <tr>
                        @foreach (var item in Model.DettaglioScheda)
                        {
                            var di = 100 / Model.NumeroG;
                            var larg = di + "%; padding:0";
                            <td class="text-center" style="width:@larg">
                                <div class="div-zoom">
                                    <div>
                                        <a href="@Url.Action("Edit", "DettaglioSchedas", new { id = item.DettaglioScheda_Id, scheda = item.Scheda_Id })">
                                            <span>@item.Giorno</span><br />
                                            <span>@item.Data.ToString("dd MMM")</span><br />
                                            <span><strong>@item.Data.ToString("HH:mm")</strong></span><br />
                                            <span class="label label-success">@item.MucoC</span><br />
                                            <span class="label label-info">@item.UteApe</span><br />
                                            <span class="label label-info">@item.UtePos</span><br />
                                            <span class="label label-info">@item.UteCon</span><br />
                                            <span class="label label-info">@item.UteInc</span><br />
                                            <span class="label label-danger">@item.Sensazione</span><br />
                                            <span class="label label-coito">@item.Coito</span><br />
                                        </a>

                                    </div>
                                </div>
                            </td>

                        }
                    </tr>
                </table>

            </div>
            <!--Legenda -->
            <div>
                <ul class="list-unstyled">
                    <li>
                        <span class="label label-success"><em>Muco.</em> Caratteristica: Opaco, Trasparente, Appiccicoso, Filante, Denso, Elastico</span><br />
                    </li>
                    <li>
                        <span class="label label-info"><em>Cervice uterina.</em> </span>
                        <ul>
                            <li>
                                <span class="label label-info">Apertura: Chiusa, Socchiusa, Aperta</span>
                            </li>
                            <li>
                                <span class="label label-info">Posizione: Alto, Medio, Basso</span>

                            </li>
                            <li>
                                <span class="label label-info">Consistenza: Dura, Soffice</span>
                            </li>
                            <li>
                                <span class="label label-info">Inclinazione: Verticale, Inclinata</span>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <span class="label label-danger">Sensazione: Asciutto, Umido, Bagnato, Lubrificato</span>
                    </li>
                    <li>
                        <span class="label label-coito">Coito: X completo, I interrotto, O senza eiaculazione, P con preservativo o diaframma </span><br />

                    </li>
                </ul>
            </div>
        </div>

        <!--Tab dati-->
        <div role="tabpanel" class="tab-pane" id="dati">
            <div >
                <table class="table table-hover">
                    <thead>

                        <tr>
                            <th>
                                Data ora rilevamento
                            </th>
                            <th>
                                Giorno
                            </th>
                            <th>
                                Temperatura
                            </th>
                            <th>
                                Perdite ematiche
                            </th>
                            <th colspan="2">
                                Muco Q.tà
                            </th>
                            <th>
                                Coito
                            </th>
                            <th>
                                Sensazione
                            </th>
                            <th colspan="4">
                                Utero<br />
                                Con. Inc. Ape. Pos.
                            </th>
                        </tr>
                    </thead>

                    @foreach (var item in Model.DettaglioScheda)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Giorno)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Temperatura)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ematic)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Muco)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MucoC)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Coito)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sensazione)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UteCon)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UteInc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UteApe)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UtePos)
                            </td>
                           <td>
                                @Html.ActionLink("Edit", "Edit", "DettaglioSchedas", new { id = item.DettaglioScheda_Id, scheda = item.Scheda_Id }, null) |

                            </td>
                        </tr>

                    }
                </table>
            </div>

        </div>
    </div>

</div>


@section Scripts{
    <script type="text/javascript">

    var result = @Html.Raw(ViewBag.DataPoints);
    var label = [];
        var temp = [];
        var muco = [];
        var ematic = [];
        var data = [];
        var mucoC = [];
    for (var i = 0; i < result.length; i++) {
        label.push(result[i].g);
        temp.push(result[i].t);
        muco.push(result[i].m);
        ematic.push(result[i].e);
        data.push(result[i].d);
        mucoC.push(result[i].mc);
        };
        //Grafico temperature
    var ctx = document.getElementById("myChart");
        let myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: data,
                datasets: [
                    {
                        label: 'Temperatura',
                        yAxisID: "B",
                        data: temp,
                        lineTension: 0,
                        pointBackgroundColor: '#000',
                        borderColor: '#000',
                        borderWidth: 2,
                        fill: false,
                    },
                    {
                        label: 'Mestruazioni',
                        yAxisID: "A",
                        data: ematic,
                        backgroundColor: 'rgb(255,0,0,0.4)',
                        pointRadius: 0,
                    },
                    {
                        label: 'Muco',
                        data: muco,
                        backgroundColor: 'rgb(96,96,96,0.4)',
                        pointRadius: 0,
                   },
                ],
            },
            options: {
                legend: {
                    display: true,
                },
                tooltips: {
                    callbacks: {
                        label: function (tooltipItem, data) {
                            var label = data.datasets[tooltipItem.datasetIndex].label || '';
                            if (label) {
                                label += ': ';
                            }
                            label += tooltipItem.yLabel;
                            return label;
                        },
                    },
                },
                scales: {
                    yAxes: [{
                        id: "A",
                        type: 'linear',
                        position: 'right',
                        tooltips: {
                            enabled: false
                        },
                        ticks: {
                            max: 50,
                            min: 0
                        },
                        display: false,
                    },
                    {
                        id: "B",
                        type: 'linear',
                        position: 'left',
                        ticks: {
                            max: 37.5,
                            min: 36,
                            stepSize: 0.1
                        },
                        display: true,
                        }],
                }
            }
        });

    </script>
}

CicleFem1/Views/Schedas/TestChart.cshtml
@model CicleFem1.Models.Scheda

@{
    ViewBag.Title = "Details";
}

<h2>Dati scheda N.@Model.Numero</h2>

<div>
    <h4>
        <span class="label label-info">
            dal @Html.DisplayFor(model => model.DataI)
            al @Html.DisplayFor(model => model.DataF)
        </span>
    </h4>
</div>

<div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#grafico" aria-controls="grafico" role="tab" data-toggle="tab">Grafico</a></li>
        <li role="presentation"><a href="#dati" aria-controls="dati" role="tab" data-toggle="tab">Dati</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="grafico">
            <canvas id="myChart" >
            </canvas>
            @*Tabelle dati sotto il grafico*@
            <table class="table table-bordered" style="font-size:0.7em">
                <tr>
                    @foreach (var item in Model.DettaglioScheda)
                    {
                        var di = 100 / Model.NumeroG;
                        var larg = di + "%";
                        <td class="text-center" style="@larg">
                            @Model.NumeroG<br />
                            @item.Giorno<br />
                            @larg
                        </td>

                    }
                </tr>
            </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="dati">
            <div >
                <table class="table table-hover">
                    <thead>

                        <tr>
                            <th>
                                Data ora rilevamento
                            </th>
                            <th>
                                Giorno
                            </th>
                            <th>
                                Temperatura
                            </th>
                            <th>
                                Perdite ematiche
                            </th>
                            <th colspan="2">
                                Muco Q.tà
                            </th>
                            <th>
                                Coito
                            </th>
                            <th colspan="4">
                                Utero<br />
                                Con. Inc. Ape. Pos.
                            </th>
                        </tr>
                    </thead>

                    @foreach (var item in Model.DettaglioScheda)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Data)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Giorno)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Temperatura)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ematic)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Muco)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MucoC)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Coito)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UteCon)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UteInc)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UteApe)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UtePos)
                            </td>
                           <td>
                                @Html.ActionLink("Edit", "Edit", "DettaglioSchedas", new { id = item.DettaglioScheda_Id, scheda = item.Scheda_Id }, null) |

                            </td>
                        </tr>

                    }
                </table>
            </div>

        </div>
    </div>

</div>
<div>
    <button type="button" id="myButton" class="btn btn-primary">
        Loading state
    </button>    
    <label id="dataP" />
</div>


@section Scripts{
    <script type="text/javascript">

    var result = @Html.Raw(ViewBag.DataPoints);
    var label = [];
        var temp = [];
        var muco = [];
        var ematic = [];
        var data = [];
    for (var i = 0; i < result.length; i++) {
        label.push(result[i].g);
        temp.push(result[i].t);
        muco.push(result[i].m);
        ematic.push(result[i].e);
        data.push(result[i].d);
    }
        $('#myButton').click(function () {
            $('#dataP').text(data);
        });

        // Define a plugin to provide data labels
        Chart.plugins.register({
            afterDatasetsDraw: function (chart, easing) {
                // To only draw at the end of animation, check for easing === 1
                var ctx = chart.ctx;

                chart.data.datasets.forEach(function (dataset, i) {
                    var meta = chart.getDatasetMeta(i);
                    if (!meta.hidden) {
                        meta.data.forEach(function (element, index) {
                            // Draw the text in black, with the specified font
                            ctx.fillStyle = 'rgb(0, 0, 0)';

                            var fontSize = 16;
                            var fontStyle = 'normal';
                            var fontFamily = 'Helvetica Neue';
                            ctx.font = Chart.helpers.fontString(fontSize, fontStyle, fontFamily);

                            // Just naively convert to string for now
                            var dataString = dataset.data[index].toString();

                            // Make sure alignment settings are correct
                            ctx.textAlign = 'center';
                            ctx.textBaseline = 'middle';

                            var padding = 5;
                            var position = element.tooltipPosition();
                            ctx.fillText(dataString, position.x, position.y - (fontSize / 2) - padding);
                        });
                    }
                });
            }
        });


        //Grafico temperature
    var ctx = document.getElementById("myChart");
        let myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: data,
                datasets: [
                    {
                        label: 'Temperatura',
                        yAxisID: "1",
                        data: temp,
                        lineTension: 0,
                        fill: false,
                    },
                    {
                        label: 'Mestruazioni',
                        yAxisID: "A",
                        data: ematic,
                        backgroundColor: 'rgb(255,0,0)',
                    },
                   {
                        label: 'Muco',
                       data: muco,
                        backgroundColor: 'rgb(96,96,96)',
                    },
                ],
            },
            options: {
                legend: {
                    display: true,
                },
                scales: {
                    yAxes: [{
                        id: "A",
                        type: 'linear',
                        position: 'right',
                        ticks: {
                            max: 50,
                            min: 0
                        },
                        display: false,
                    },
                        {
                        id: "1",
                        type: 'linear',
                        position: 'left',
                       ticks: {
                            max: 37.5,
                            min: 36,
                            stepSize: 0.1,
                            display: false,
                        },
                        }],
                }
            }
        });

    </script>
}