CicleFem1/Controllers/UserAdminController.cs
using CicleFem1.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.IO;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CicleFem1.Controllers
{
    public class UsersAdminController : Controller
    {

        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            ViewBag.UtentiCount = UserManager.Users.Count();
            return View(await UserManager.Users.ToListAsync());
        }

        [Authorize]
        public ActionResult IndexUs()
        {
            var uid = User.Identity.GetUserId();
            ViewBag.Uid = uid;
            return View();
        }

        //
        // GET: /Users/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);
            foreach (var rol in ViewBag.RoleNames)
            {
                @ViewBag.Rol = rol;
            }
            return View(user);
        }

        //
        // GET: /Users/Create
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            ViewBag.Uid = id;
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                Nome = user.Nome,
                Cognome = user.Cognome,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Email,Nome,Cognome")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.Nome = editUser.Nome;
                user.Cognome = editUser.Cognome;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }


        [Authorize]
        public async Task<ActionResult> EditUs(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUsViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                Nome = user.Nome,
                Cognome = user.Cognome,
            });
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditUs([Bind(Include = "Id,Email,Nome,Cognome")] EditUsViewModel editUser)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.Nome = editUser.Nome;
                user.Cognome = editUser.Cognome;

                await UserManager.UpdateAsync(user);
                return RedirectToAction("IndexUs");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        [Authorize]

CicleFem1/Views/UsersAdmin/Create.cshtml
@model CicleFem1.Models.RegisterViewModel

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Nuovo</h4>
    <hr class="hr1" />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Nome, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Cognome, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Cognome, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">
            Select User Role
        </label>
        <div class="col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CicleFem1/Views/UsersAdmin/Delete.cshtml
@model CicleFem1.Models.ApplicationUser

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>

<div>
    <h3>Sei sicuro di voler cancellare questo utente?</h3>
    <hr class="hr1" />
    <div class="row">
        <div class="col col-md-3">
                <img class="img-responsive" src="@Url.Content("~/Content/Immagini/Utenti/Anonimous.jpg")" /><br />
        </div>
        <div class="col col-md-9">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.UserName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.UserName)
                </dd>
            </dl>

        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancella" class="btn btn-danger" />
            @Html.ActionLink("Annulla", "Index", null, new { @class = "btn btn-success" })
        </div>
    }
</div>

CicleFem1/Views/UsersAdmin/Details.cshtml
@model CicleFem1.Models.ApplicationUser

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>
<div>
    <hr class="hr1" />
    <div class="row">
        <div class="col col-md-2">
            <img class="img-responsive" src="@Url.Content("~/Content/Immagini/Utenti/anonimous.jpg")" />

        </div>
        <div class="col col-md-3">
            @Html.DisplayFor(model => model.UserName)<br />
        </div>
    </div>
</div>
<hr class="hr1" />
<h4>Ruoli di appartenenza</h4>
@Html.Display(User.Identity.Name.ToString())
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>Nessun ruolo assegnato a questo utente</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Modifica", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Torna alla lista", "Index")
</p>

CicleFem1/Views/UsersAdmin/Edit.cshtml
@model CicleFem1.Models.EditUserViewModel

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>

<h4>Modifica</h4>
<hr class="hr1" />
<div class="row">
    <div class="col col-md-8">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Nome)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Cognome, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Cognome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Cognome)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        @Html.Label("Roles", new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @foreach (var item in Model.RolesList)
                {
                                <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                @Html.Label(item.Value, new { @class = "control-label" })<br />

                            }
                        </div>


                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Salva" class="btn btn-success" />
                        @Html.ActionLink("Lista utenti", "Index", null, new { @class = "btn btn-danger" })<br />
                        @Html.ActionLink(" ", null, null, null, new { href = Request.UrlReferrer, @class = "glyphicon glyphicon-arrow-left h2" })

                    </div>
                </div>
            </div>
        }

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('.datepicker').datepicker("option", "dateFormat", "dd/mm/yyyy");
    </script>

}

CicleFem1/Views/UsersAdmin/Index.cshtml
@model IEnumerable<CicleFem1.Models.ApplicationUser>

@{
    ViewBag.Title = "Gestione utenti";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col col-md-8">
        <div class="btn btn-primary"><span class="badge">@ViewBag.UtentiCount</span> Registràti</div>
    </div>
    <div class="col col-md-4 text-right">
        @Html.ActionLink(" ", "Index", "Squadres", null, new { @class = "glyphicon glyphicon-knight", title = "Gestione squadre" })
    </div>
</div>
<p>
</p>
<table class="table table-hover">
    <tr>
        <th>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>@Html.DisplayNameFor(model => model.Nome)</th>
        <th>@Html.DisplayNameFor(model => model.Cognome)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (File.Exists(@Server.MapPath("/Content/Immagini/Utenti/" + @Html.DisplayFor(modelItem => item.Id) + ".jpg")))
                {
                    <a class="text-danger" href="@Url.Action("FotoProfilo1", "UsersAdmin", new { id = item.Id })" title="Modifica foto profilo"><span class="glyphicon glyphicon-pencil"></span></a>
                    <img class="img-usr" src="@Url.Content("~/Content/Immagini/Utenti/" + @Html.DisplayFor(modelItem => item.Id) + ".jpg")" />
                }
                else
                {
                    <a class="text-danger" href="@Url.Action("FotoProfilo1", "UsersAdmin", new { id = item.Id })" title="Aggiungi foto profilo"><span class="glyphicon glyphicon-plus"></span></a>
                    <img class="img-usr" src="@Url.Content("~/Content/Immagini/Utenti/Anonimous.jpg")" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cognome)
            </td>
            <td>
                @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil", @title = "Modifica" })
                @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "glyphicon glyphicon-remove text-danger", @title = "Cancella" })


            </td>
        </tr>
    }

</table>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/Scripts/jquery.filtertable.min.js")
<script>
        $(document).ready(function () {
            $('table').filterTable();
        });
</script>